// GENERATED by scripts/sync-foundation-tokens.mjs from kttipay/designsystem v0.3.0 web/tokens.ts — DO NOT EDIT. Refresh: npm run sync:foundation -- --tag vX.Y.Z

// Subset of the foundation used by the checkout button and the mock showcase:
//   brand.primary <- colorsLight.brand.primary (burgundy/600)
//   brand.secondary <- colorsLight.brand.secondary (orange/500)
//   palette.burgundy.700 <- palette.burgundy.700 (hover shade for brand.primary)
//   palette.base.white <- palette.base.white
//   text.primaryInverse <- colorsLight.text.primaryInverse (text on brand.primary)

export const FOUNDATION_TAG = 'v0.3.0';

export const foundation = {
  brand: {
    primary: '#4A0324',
    secondary: '#FE572A',
  },
  palette: {
    burgundy: {
      700: '#3B021D',
    },
    base: {
      white: '#FFFFFF',
    },
  },
  text: {
    primaryInverse: '#FFFFFF',
  },
} as const;
