import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';
import { FOUNDATION_TAG, foundation } from '../foundation/brand.generated.js';

const read = (relative: string): string =>
  readFileSync(fileURLToPath(new URL(relative, import.meta.url)), 'utf8');

const lock = JSON.parse(read('../../foundation.lock.json')) as { repo: string; tag: string; source: string };
const generated = read('../foundation/brand.generated.ts');
const headerTag = /^\/\/ GENERATED by scripts\/sync-foundation-tokens\.mjs from kttipay\/designsystem (v\d+\.\d+\.\d+) web\/tokens\.ts/.exec(generated)?.[1];

describe('foundation tokens', () => {
  it('generated header tag matches foundation.lock.json (refresh with npm run sync:foundation, never by hand)', () => {
    expect(headerTag).toBe(lock.tag);
    expect(FOUNDATION_TAG).toBe(lock.tag);
  });

  it('vendors opaque hex colours for every role the button uses', () => {
    for (const value of [
      foundation.brand.primary,
      foundation.brand.secondary,
      foundation.palette.burgundy[700],
      foundation.palette.base.white,
      foundation.text.primaryInverse,
    ]) {
      expect(value).toMatch(/^#[0-9A-F]{6}$/);
    }
  });
});
